
INSERT INTO ADMINISTRATOR 
(ID, EMAIL, PASSWORD, DATEREGISTRATION, SECONDARYADMINISTRATOR)
VALUES
(200, "demonstration@test.ru", "test" , "2016-01-01" , FALSE);

INSERT INTO PRICE 
(ID, NAME, MAXAMOUNTUSERS, MAXAMOUNTSITES, DURATIONOFPRICEDAY)
VALUES
(200, "FREE", 3 ,5 , 100);

INSERT INTO ADMINISTRATORPRICE 
(IDPRICE, IDADMINISTRATOR, DATEOFPAY)
VALUES
(200,200 , "2016-01-01");
