CREATE TABLE ADMINISTRATORPERSON (
	ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
	IDPERSON int NOT NULL,
	IDADMINISTRATOR int NOT NULL
);


INSERT INTO ADMINISTRATORPERSON 
(IDPERSON, IDADMINISTRATOR)
VALUES
(5001, 5000);


INSERT INTO ADMINISTRATORPERSON 
(IDPERSON, IDADMINISTRATOR)
VALUES
(5002, 5000);

INSERT INTO ADMINISTRATORPERSON 
(IDPERSON, IDADMINISTRATOR)
VALUES
(5003, 5000);
