CREATE TABLE ADMINISTRATORPERSON (
	ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
	IDPERSON int NOT NULL,
	IDADMINISTRATOR int NOT NULL
);

/*
INSERT INTO ADMINISTRATORPRICE 
(IDPERSON, IDADMINISTRATOR)
VALUES
(1, 1);
*/