CREATE TABLE ADMINISTRATORPRICE (
	ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
	IDPRICE int NOT NULL,
	IDADMINISTRATOR int NOT NULL,
	DATEOFPAY DATETIME NOT NULL
);

/*
INSERT INTO ADMINISTRATORPRICE 
(IDPRICE, IDADMINISTRATOR, DATEOFPAY)
VALUES
(1, 1 , "2016-01-01");
*/