CREATE TABLE `SITE` (
	`ID` int auto_increment PRIMARY KEY NOT NULL,
	`NAME` varchar(256) NOT NULL,
    `STARTDATESTATISTICS` DATETIME
);

CREATE TABLE `PERSONPAGERANK` (
	`ID` int PRIMARY KEY auto_increment NOT NULL,
	`PERSONID` int NOT NULL,
	`PAGEID` int NOT NULL,
	`RANK` int NOT NULL
);

CREATE TABLE PERSON (
	`ID` int PRIMARY KEY auto_increment NOT NULL,
	`NAME` varchar(2048) NOT NULL
);

CREATE TABLE `PAGE` (
	`ID` int PRIMARY KEY auto_increment NOT NULL,
	`URL` varchar(2048) NOT NULL,
	`SITEID` int NOT NULL,
	`FOUNDDATETIME` DATETIME,
	`LASTSCANDATE` DATETIME,
    `HTML` MEDIUMTEXT
);

CREATE TABLE `KEYWORD` (
	`ID` int PRIMARY KEY auto_increment NOT NULL,
	`NAME` varchar(2048) NOT NULL,
	`PERSONID` int NOT NULL
);
